spring:
  application:
    name: commerce
  datasource:
    url: jdbc:postgresql://localhost:5432/preonboarding_202505
    username: postgres
    password: 2297
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
